# Generated by Django 4.1.2 on 2022-10-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('DI', 'disponible'), ('OC', 'ocupada'), ('MA', 'mantenimiento'), ('LI', 'limpieza'), ('DE', 'deshabilitada')], default='DE', max_length=2)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('informacion', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
