# Generated by Django 4.1.2 on 2022-10-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_habitaciones_delete_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediosPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacion', models.CharField(default='Sin datos de pago', max_length=250)),
                ('medios', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.mediospago')),
            ],
        ),
    ]
