# Generated by Django 4.1.2 on 2022-10-16 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mediospago_datospago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('DE', 'Desconocida'), ('PR', 'Producto'), ('SE', 'Servicio')], default='DE', max_length=2)),
                ('agregado', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='estado',
            field=models.CharField(choices=[('DI', 'Disponible'), ('OC', 'Ocupada'), ('MA', 'Mantenimiento'), ('LI', 'Limpieza'), ('DE', 'Deshabilitada')], default='DE', max_length=2),
        ),
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reservada', models.DateField()),
                ('costo_reservado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('correo', models.EmailField(max_length=254)),
                ('datos_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.datospago')),
                ('habitaciones', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.habitaciones')),
            ],
        ),
    ]
