# Generated by Django 4.1.2 on 2022-10-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_agregados_alter_habitaciones_estado_reservaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelTransaccionAgregado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelTransaccionReservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateField()),
                ('detalles', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='agregados',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='datospago',
            name='medios',
        ),
        migrations.RemoveField(
            model_name='habitaciones',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='reservaciones',
            name='costo_reservado',
        ),
        migrations.RemoveField(
            model_name='reservaciones',
            name='datos_pago',
        ),
        migrations.RemoveField(
            model_name='reservaciones',
            name='habitaciones',
        ),
    ]
