# Generated by Django 4.1.2 on 2022-10-16 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_reltransaccionagregado_reltransaccionreservacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregados',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='datospago',
            name='medios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.mediospago'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reltransaccionagregado',
            name='agregado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.agregados'),
        ),
        migrations.AddField(
            model_name='reltransaccionagregado',
            name='transaccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.transacciones'),
        ),
        migrations.AddField(
            model_name='reltransaccionreservacion',
            name='reservacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.reservaciones'),
        ),
        migrations.AddField(
            model_name='reltransaccionreservacion',
            name='transaccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.transacciones'),
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='costo_reservado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='datos_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.datospago'),
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='habitaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.habitaciones'),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
