# Generated by Django 4.1.2 on 2022-10-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_reservaciones_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='fecha_entrega',
            field=models.DateField(default='2022-10-20'),
        ),
    ]
