# Generated by Django 4.1.2 on 2022-10-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_reservaciones_fecha_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaciones',
            old_name='fecha_reserva',
            new_name='fecha_reservada',
        ),
        migrations.RemoveField(
            model_name='habitaciones',
            name='cant_adultos',
        ),
        migrations.RemoveField(
            model_name='habitaciones',
            name='cant_ninos',
        ),
        migrations.RemoveField(
            model_name='reservaciones',
            name='fecha_entrega',
        ),
    ]
