# Generated by Django 4.1.2 on 2022-10-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_fecha_reserva_reservaciones_fecha_reservada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaciones',
            old_name='fecha_reservada',
            new_name='fecha_reserva',
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
