# Generated by Django 4.1.2 on 2022-10-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_fecha_reservada_reservaciones_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='cant_adultos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='cant_ninos',
            field=models.IntegerField(default=0),
        ),
    ]
