# Generated by Django 4.1.2 on 2022-10-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_habitaciones_cant_adultos_habitaciones_cant_ninos'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='foto_ref',
            field=models.ImageField(blank=True, null=True, upload_to='archivos/fotos'),
        ),
    ]
