# Generated by Django 4.1.2 on 2022-10-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_habitaciones_foto_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='estado',
            field=models.CharField(choices=[('AC', 'Aceptada'), ('RE', 'Rechazada'), ('PR', 'Procesando')], default='PR', max_length=2),
        ),
    ]
