# Generated by Django 4.1.2 on 2022-10-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_reservaciones_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaciones',
            name='datos_pago',
        ),
        migrations.AddField(
            model_name='agregados',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='medio_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('DE', 'Tarjeta de debito'), ('CR', 'Tarjeta de credito'), ('CH', 'Cheque'), ('RE', 'Referencia bancaria'), ('TR', 'Transferencia bancaria')], default='EF', max_length=2),
        ),
        migrations.DeleteModel(
            name='DatosPago',
        ),
        migrations.DeleteModel(
            name='MediosPago',
        ),
    ]
