# Generated by Django 4.1.2 on 2022-11-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_reservaciones_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='estado',
            field=models.CharField(choices=[('FI', 'Finalizada'), ('CA', 'Cancelada'), ('VA', 'Validando')], default='VA', max_length=2),
        ),
    ]
