# Generated by Django 4.1.2 on 2022-11-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_reservaciones_datos_pago_and_more'),
        ('home', '0016_transacciones_estado'),
    ]

    operations = [
    ]
