# Generated by Django 4.1.2 on 2022-11-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_merge_20221108_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitaciones',
            name='foto_ref',
            field=models.ImageField(blank=True, null=True, upload_to='apps/static/archivos/fotos'),
        ),
    ]
