# Generated by Django 4.1.2 on 2022-11-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_habitaciones_foto_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitaciones',
            name='foto_ref',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
