# Generated by Django 4.1.2 on 2022-11-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_habitaciones_foto_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion_rol', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='reltransaccionagregado',
            name='agregado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.agregados'),
        ),
        migrations.AlterField(
            model_name='reltransaccionagregado',
            name='transaccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.transacciones'),
        ),
        migrations.AlterField(
            model_name='reltransaccionreservacion',
            name='reservacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.reservaciones'),
        ),
        migrations.AlterField(
            model_name='reltransaccionreservacion',
            name='transaccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.transacciones'),
        ),
        migrations.AlterField(
            model_name='reservaciones',
            name='habitaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.habitaciones'),
        ),
        migrations.CreateModel(
            name='UsuariosHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('correo_usuario', models.EmailField(max_length=254)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.roles')),
            ],
        ),
    ]
