# Generated by Django 4.1.2 on 2022-11-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_roles_alter_reltransaccionagregado_agregado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='descripcion_rol',
            field=models.CharField(max_length=50),
        ),
    ]
