# Generated by Django 4.1.2 on 2022-11-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_roles_descripcion_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioshotel',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
